#! /bin/bash

# assign classes to hosts based on their hostname

# do not use this if a menu will be presented
[ "$flag_menu" ] && exit 0

# use a list of classes for our demo machine
case $HOSTNAME in
    faiserver)
        echo "FAIBASE DEBIAN DEMO FAISERVER" ;;
    debian)
        echo "FAIBASE DEBIAN DEMO XORG GNOME HA HA_SECURE_ERASE";;
    *)
        echo "FAIBASE DEBIAN DEMO XORG GNOME HA HA_SECURE_ERASE" ;;
esac
